### ISSUE TITLE
Twitterにも流れるオプションをつける

### ISSUE THREAD

**Issue by ryokohbato** [kmc-jp/GodUploader-graphql#106]
#  なぜ
他の団体と比較して、KMCは対外的な活動が少なく感じる。Twitterに作品を投稿するオプションをつけてTwitterを動かすとともに宣伝効果も高めていきたい

**Comment by ryokohbato** [comment]
投稿時の名義も自由に変えられるようにするとして、投稿用のメッセージを考えないと

**Comment by utgwkk** [comment]
サーバーサイド側の実装を巻き取ります。

# 検討
## GraphQLスキーマ

共有設定の単位ごとに型を分けて構造化しておくとよいのでは。
`shareOption` っていう名前でSlack共有の設定を受け取ってるのが邪魔だけど、まあいったんあとで見る。

```graphql
input UploadArtworkInput {
  """Twitterへの共有設定。nullのときは共有しない"""
  twitterShareOption: TwitterShareOption
  # 中略
}

type TwitterShareOption {
  """作品をTwitterに共有するかどうか。falseのときは共有されず、他のフィールドも無視される。"""
  share: Boolean!

  """Twitterに共有する際の投稿者の表示名。nullのときはKMCID？ 投稿用の名義をアカウントごとに設定できるようにしてもよいのかも。"""
  username: String
}
```

## DBスキーマ

投稿用の名義をアカウントごとに設定できるようにするかどうかによって変わりそう。

## Twitter APIクライアント

[tweepy](https://www.tweepy.org/)でいいと思う。画像アップロード周りがどうなるかは調べておく。

## 認証情報

KMC_JPで新しいTwitterアプリを作ってキー一式を用意する。手元でのお試しには適当なアカウントとアプリを用意したらよさそう。

**Comment by ryokohbato** [comment]
お願いしますー

**Comment by utgwkk** [comment]
ひきつづき検討

# Twitterに上げる画像のサイズ

[Media Best Practices | Docs | Twitter Developer Platform](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)にあるように容量制限がある。
サムネイル画像だとサイズが小さすぎるので、容量超過するときだけ適当に大きさ1/2ぐらいにしてアップロードしたらいい？

# メッセージの文字数制限

ちゃんとやるならtwitter-textで計算する必要があるけど、どこまでやるか。ユーザー名ぐらいしか入らないなら適当な文字数制限を設ければよさそう。タイトルも入るとちょっと大変かも。

**Comment by ryokohbato** [comment]
タイトル、確かに大変そう
そんなに字数いっぱい使うこともなさそうなので、余裕を持って判定しておけば大丈夫そうな感じはあります

**Comment by ryokohbato** [comment]
いい感じっぽいので close しますね
